{{- if and .Values.fluentd.enabled .Values.fluentd.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fluent.fullname" . }}-fluentd-buffer
  labels:
    {{- include "fluent.fluentd.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.fluentd.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- if .Values.fluentd.persistence.storageClass }}
  storageClassName: {{ .Values.fluentd.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.fluentd.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fluent.fullname" . }}-fluentd-logs
  labels:
    {{- include "fluent.fluentd.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.fluentd.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- if .Values.fluentd.persistence.storageClass }}
  storageClassName: {{ .Values.fluentd.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: 1Gi
{{- end }}
