{{- if .Values.fluentBit.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluent.fullname" . }}-fluent-bit-sa
  labels:
    {{- include "fluent.fluentBit.labels" . | nindent 4 }}
{{- end }}
