{{- if .Values.fluentd.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluent.fullname" . }}-fluentd-sa
  labels:
    {{- include "fluent.fluentd.labels" . | nindent 4 }}
{{- end }}
